### ISSUE TITLE
Time Complexity

### ISSUE THREAD

**Issue by bhupendersinghh** [alallo/FrogBlocks#1]
Since the worst case complexity for the solution would be O(n^2), would it work for the given constraints without producing TLE?

**Comment by alallo** [comment]
The TLE has not been considered for this solution to be honest. But I don't see that as a problem.

**Comment by bhupendersinghh** [comment]
Generally, for constraints n greater than 10^5, O(nlogn) or O(n) works without producing TLE. 
Thanks for the solution!
